### ISSUE TITLE
The 5 Errors of Dandere2x 3.7.2 (3.3.1 is better?)

### ISSUE THREAD

**Issue by DCGYT** [akai-katto/dandere2x#281]
![Title](https://user-images.githubusercontent.com/98280315/199124757-c71bbff8-5ff9-474c-af82-03b8c5ba5659.png)
I have decided to recapitulate all the bugs I have found all this time in just one post for ease of information.

### Issues Table - Less is better
|Issue|Blur|Color|Dots|Fade|Lines|Noise|Spots|Other|Total|Time|
|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|---:|
|1.3.1|3|1|3|1|1|2|0|2|13|1:46|
|1.8   |3|2|3|1|2|1|0|2|14|2:39|
|1.9   |2|2|2|1|3|3|0|3|16|2:50|
|3.0.3|2|2|1|3|3|2|1|0|14|6:20|
|3.3.1|0|2|2|0|2|0|2|0|8|5:58|
|3.6   |0|2|3|0|0|1|3|1|10|5:28|
|3.7.2|0|2|3|0|2|1|3|0|11|5:06|

**Blur**: It is if the final video looks blurry compared to the best versions.
**Color:** Color change from the original video
**Dots:** In scenes with linear movement, the points remain at the corners of the blocks.
**Fade:** In fade transitions, the blocks do not change. (3.6+ something similar happens because of the noise).
**Lines**: In bright places flashing lines suddenly appear on the edges of the blocks.
**Noise**: This is the image noise, very noticeable on TN screens.
**Spots**: Dark edges in the grid and blocks that do not change color.
**Other**: (1.3.1/1.8) Some blocks are slow to change. (1.9) Grid everywhere. (3.6) Time limit on slower PCs.

**Check it out:** https://drive.google.com/drive/folders/1euz0rhq-M-dQYPQME7QSTMTO9rfH2EDn?usp=share_link

### 3.7.2 Feedback

Version 3.7.2 fixed the time limit on less powerful computers from 3.6, however, it brought back the lines problem, which was the only reason for using 3.6 that was going to allow me to not scale the same video 2 times. So I think this version was a step backwards from the previous one.

Another quite important bug is the spots in the video, the more the version advanced, the worse they got. In version 3.0.3 you could see dark edges in the grid, but already in 3.3 there started to be bugs in the color of the blocks, flickering slightly in color, and this became even more noticeable since 3.6.

I would also like to fix the issue of the dots in the corners, since for those scenes I have to use version 3.0.3, which has worse quality.

In minimal errors there is the issue that now again there is noise in the image, the plain colors now do not look completely smooth and in the GUI the letters are white on a white background.

For now I feel that the best version is 3.3.1, because it has the least bugs.

**Comment by akai-katto** [comment]
You don't realize how valuable this feedback is for me. I'll use this as a reference point on how to fix current dandere2x as well as drawing inspiration from the new dandere2x. 

Seriously, thank you. I'm very impressed by the effort you put into this.

**Comment by akai-katto** [comment]
What settings were these used under?

**Comment by DCGYT** [comment]
@akai-katto I used maximum block and maximum image quality.

**Comment by akai-katto** [comment]
Hm, bigger block size typically is worse, I wish I had specified this before you went into it. Thanks though. 

Curious to see if smaller block size (say 20?) has any improvement for your results?

**Comment by DCGYT** [comment]
@akai-katto I don't like to use low blocks, because you can easily see the grid. For example, lines, using a low block makes them more noticeable. But I will try it now.

**Comment by DCGYT** [comment]
@akai-katto I have tested 3.7.2 with block 20 and it is still the same.
I uploaded the video of the test in Google Drive in the folder "Other Tests".

![image](https://user-images.githubusercontent.com/98280315/205462018-1d2615a4-1dc5-401e-9c20-4e7a5d955992.png)![image](https://user-images.githubusercontent.com/98280315/205462038-5ee194a0-4aaf-4e63-94b9-1f7840ad1e8c.png)![image](https://user-images.githubusercontent.com/98280315/205462116-d255075a-cc73-4cf0-be03-42246596af4a.png)
![image](https://user-images.githubusercontent.com/98280315/205462052-50e3e116-fc94-4c79-afd7-adc7728256c0.png)

**Comment by akai-katto** [comment]
I got the same results.

I'll take a break from dandere2x rework to work on this.

**Comment by akai-katto** [comment]
https://drive.google.com/file/d/1Vq7QvMOdn7yk1PWLYX5QPniD3OEPlx8v/view?usp=sharing

Would you say this looks less noisy, or the same (this is dandere2x rework WIP)

**Comment by DCGYT** [comment]
@akai-katto A great improvement to the contrast which remains the same as 1.3.1! although the color still varies from the original tone, which I think must be difficult to correct.

The noise remains exactly the same. In the final part of the video is the key to see the noise. Or as I called it (spots). Maybe it would be better to use the 60 block, it's the same as the 20 but easier to identify.

![image](https://user-images.githubusercontent.com/98280315/205464643-fab9eee4-3521-4408-b647-678d9ddb2883.png)

**Comment by akai-katto** [comment]
how do you edit the photo to dramatize the spots? I can barely notice them on my VA monitor, so I'm trying to work around replicating it locally

**Comment by akai-katto** [comment]
here's blocksize 60 on new dandere2x, if you want to share your thoughts 

https://drive.google.com/file/d/1dq7fQsWbNsmA16LyTSuv27Ts3MBjq_7V/view?usp=sharing

**Comment by DCGYT** [comment]
@akai-katto I use a paid program called Affinity Photo 2, it has a 30 day trial version. But on the internet I found an online tool, this one is from posterize, testing values like 40 would work I guess. I will look for a better tool. Because previously I used a difference filter with DaVinci Resolve and it worked better.

For now it may work: https://pinetools.com/posterize-image
![image](https://user-images.githubusercontent.com/98280315/205464917-f5ae3617-6891-425a-895d-e1a88119b16a.png)

**Comment by DCGYT** [comment]
> here's blocksize 60 on new dandere2x, if you want to share your thoughts
> 
> https://drive.google.com/file/d/1dq7fQsWbNsmA16LyTSuv27Ts3MBjq_7V/view?usp=sharing

Access denied xd

**Comment by akai-katto** [comment]
shared

**Comment by DCGYT** [comment]
@akai-katto I think the best program to see the noise is "avidemux", using a filter: Artistic > Dynamic Threshold.
![image](https://user-images.githubusercontent.com/98280315/205465509-bf948d77-bcf6-4c0e-a57e-61dd39f516e8.png)

**Comment by DCGYT** [comment]
@akai-katto With block 60. Curiously, I did not see white dots, but I did see a lot of noise.
![image](https://user-images.githubusercontent.com/98280315/205465704-0a81af21-88c3-4df4-9863-86d77d087a94.png)

**Comment by DCGYT** [comment]
@akai-katto I don't know why I had not used this program before for testing.
![image](https://user-images.githubusercontent.com/98280315/205465763-e116297a-a570-44b2-9967-c87077a040b0.png)

**Comment by akai-katto** [comment]
Does the input video demonstrate the same noise? I'm wondering if it's an input video error or dandere2x error. Hoping it's an input video error but we'll see.

**Comment by DCGYT** [comment]
@akai-katto This is what the original video looks like. It is noticeable that the noise is different, since in this one it is quite small, while the Dandere2x one is mostly grid-based.
![image](https://user-images.githubusercontent.com/98280315/205466018-b35fe20b-4898-4ac7-8775-ce4b7ae77ede.png)

**Comment by akai-katto** [comment]
Thank you for your input. I'll research this tonight

**Comment by akai-katto** [comment]
Would you mind trying the new dandere2x prototype out, and leaving your thoughts on it? https://www.reddit.com/r/Dandere2x/comments/zctvfo/dandere2x_rework_proof_of_concept_ready_for/

**Comment by DCGYT** [comment]
@akai-katto I'll try it now, I only use Microsoft Defender so hopefully it won't be a problem xd.

**Comment by DCGYT** [comment]
@akai-katto At the moment it strikes me that it is using the integrated graphics xd, maybe I should start the program with the Nvidia manually later.
![image](https://user-images.githubusercontent.com/98280315/205802172-888617b4-f69a-4193-9b45-efd36cd3dc41.png)

**Comment by akai-katto** [comment]
let me fix this

**Comment by akai-katto** [comment]
https://github.com/akai-katto/dandere2x-python-rework/releases/tag/0.0.2

You should be able to download the latest versioning allowing selecting GPU in 0.0.2.1.

Simply goto your config_files, open up output_options.yaml, and change the following variables 

```
waifu2x_ncnn_vulkan:
  model_name: "models-cunet"
  tile_size: 200  # note: if you get black images try lowering this tile argument to some lower value.
  pre_padding: 18
  client_ports:
    client0:
      gpuid: 0
      receive_port: 43560
      send_port: 43561
    client1:
      gpuid: 0
      receive_port: 43562
      send_port: 43563
    client2:
      gpuid: 0
      receive_port: 43564
      send_port: 43565
    client3:
      gpuid: 0
      receive_port: 43566
      send_port: 43567
```

->

```
waifu2x_ncnn_vulkan:
  model_name: "models-cunet"
  tile_size: 200  # note: if you get black images try lowering this tile argument to some lower value.
  pre_padding: 18
  client_ports:
    client0:
      gpuid: 1
      receive_port: 43560
      send_port: 43561
    client1:
      gpuid: 1
      receive_port: 43562
      send_port: 43563
    client2:
      gpuid: 1
      receive_port: 43564
      send_port: 43565
    client3:
      gpuid: 1
      receive_port: 43566
      send_port: 43567
```
